prefix = "."
stop-words = "stopwords.txt"

dataset = "SarsCoV2"
corpus = "line.toml"
index = "idx2"



[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "queries-test.txt"
query-id-start = 1

